-- Tạo bảng bien_ban_chu_ky
CREATE TABLE bien_ban_chu_ky (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- Tự động tăng
  bien_ban_id bigint NOT NULL,                            -- Khóa ngoại đến bien_ban_xac_minh_su_co
  thanh_vien_id bigint NOT NULL,                          -- Khóa ngoại đến bien_ban_thanh_vien
  duong_dan_file text,                                   -- Đường dẫn file
  thoi_gian_ky timestamp with time zone,                 -- Thời gian ký
  created_at timestamp with time zone DEFAULT now(),
  FOREIGN KEY (bien_ban_id) REFERENCES bien_ban_xac_minh_su_co(id),
  FOREIGN KEY (thanh_vien_id) REFERENCES bien_ban_thanh_vien(id)
);

-- Policy: Cho phép tất cả người dùng đọc, chỉ owner được sửa/xóa
CREATE POLICY "bien_ban_chu_ky: Select all" ON bien_ban_chu_ky
  FOR SELECT USING (true);
CREATE POLICY "bien_ban_chu_ky: Insert" ON bien_ban_chu_ky
  FOR INSERT WITH CHECK (auth.uid() IS NOT NULL);
CREATE POLICY "bien_ban_chu_ky: Update" ON bien_ban_chu_ky
  FOR UPDATE USING (auth.uid() IS NOT NULL);
CREATE POLICY "bien_ban_chu_ky: Delete" ON bien_ban_chu_ky
  FOR DELETE USING (auth.uid() IS NOT NULL);
