-- Tạo bảng bien_ban_xac_minh_su_co
CREATE TABLE bien_ban_xac_minh_su_co (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- Tự động tăng
  thoi_gian_bat_dau timestamp with time zone NOT NULL,    -- Thời gian bắt đầu
  thoi_gian_ket_thuc timestamp with time zone,            -- Thời gian kết thúc
  dia_diem text,                                          -- Địa điểm
  noi_dung_xac_minh text,                                 -- Nội dung xác minh
  ket_qua_xac_minh text,                                  -- Kết quả xác minh
  y_kien_tham_gia text,                                   -- Ý kiến tham gia
  so_trang int,                                           -- Số trang
  so_ban int,                                             -- Số bản
  created_at timestamp with time zone DEFAULT now(),       -- Thời gian tạo
  updated_at timestamp with time zone DEFAULT now()        -- Thời gian cập nhật
);

-- Policy: Cho phép tất cả người dùng đọc, chỉ owner được sửa/xóa
CREATE POLICY "bien_ban_xac_minh_su_co: Select all" ON bien_ban_xac_minh_su_co
  FOR SELECT USING (true);
CREATE POLICY "bien_ban_xac_minh_su_co: Insert" ON bien_ban_xac_minh_su_co
  FOR INSERT WITH CHECK (auth.uid() IS NOT NULL);
CREATE POLICY "bien_ban_xac_minh_su_co: Update" ON bien_ban_xac_minh_su_co
  FOR UPDATE USING (auth.uid() IS NOT NULL);
CREATE POLICY "bien_ban_xac_minh_su_co: Delete" ON bien_ban_xac_minh_su_co
  FOR DELETE USING (auth.uid() IS NOT NULL);
