-- Tạo bảng bien_ban_thanh_vien
CREATE TABLE bien_ban_thanh_vien (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- Tự động tăng
  bien_ban_id bigint NOT NULL,                            -- Khóa ngoại đến bien_ban_xac_minh_su_co
  ho_ten text NOT NULL,                                   -- Họ tên
  chuc_vu text,                                           -- Chức vụ
  don_vi text,                                            -- Đơn vị
  vai_tro text NOT NULL CHECK (
    vai_tro IN ('CHU_TRI', 'THANH_VIEN_DOAN', 'NGUOI_CHUNG_KIEN', 'NGUOI_THAM_DU', 'NGUOI_LAP_BIEN_BAN')
  ),                                                     -- Vai trò
  ky_ten boolean DEFAULT FALSE,                           -- Ký tên
  created_at timestamp with time zone DEFAULT now(),
  FOREIGN KEY (bien_ban_id) REFERENCES bien_ban_xac_minh_su_co(id) ON DELETE CASCADE
);

-- Policy: Cho phép tất cả thao tác CRUD
CREATE POLICY "bien_ban_thanh_vien: Select all" ON bien_ban_thanh_vien
  FOR SELECT USING (true);
CREATE POLICY "bien_ban_thanh_vien: Insert" ON bien_ban_thanh_vien
  FOR INSERT WITH CHECK (true);
CREATE POLICY "bien_ban_thanh_vien: Update" ON bien_ban_thanh_vien
  FOR UPDATE USING (true);
CREATE POLICY "bien_ban_thanh_vien: Delete" ON bien_ban_thanh_vien
  FOR DELETE USING (true);
