/**
 * Danh mục tên kết quả báo động cận lâm sàng (IPSG.02.00) - danh mục mẫu.
 * Bệnh viện cập nhật theo Danh mục kết quả báo động đã được Giám đốc Bệnh viện
 * phê duyệt (Phụ lục I của Quy trình QLCL.QT.16).
 */
export const CRITICAL_RESULT_NAMES = [
  'Albumin',
  'ALT (Alanin Amino Transferase)',
  'AST (Aspartat Amino Transferase)',
  'Amylase máu',
  'Ammoniac',
  'Bilirubin TP',
  'Bilirubin TT',
  'GGT',
  'Glucose',
  'Canci TP',
  'Cholesterol',
  'HDL- Cholesterol',
  'LDL- Cholesterol',
  'LDH',
  'CK hoặc CPK (Creatinkinase hoặc Creatin Phospho kinase)',
  'CK-MB',
  'Creatinin',
  'HS- CRP',
  'Na+',
  'K+',
  'Cl-',
  'Protein TP',
  'Sắt',
  'Triglycerid',
  'Ure',
  'ALP',
  'HbA1C',
  'Hs-Troponin I',
  'BNP',
  'Vitamin B12',
  'NT- Pro BNP',
  'FT3 (Free T3)',
  'FT4 (Free T4)',
  'TSH',
  'Tg',
  'Anti- Tg',
  'WBC',
  'Neutrophil',
  'HGB',
  'PLT',
  'PT INR',
  'APTT s',
  'Fibrinogen',
  'D-Dimer',
  'Vi khuẩn nuôi cấy và định danh hệ thống tự động (Vị trí 1/hiếu khí)',
  'Vi khuẩn nuôi cấy và định danh hệ thống tự động (Vị trí 2/kỵ khi tùy tiện)',
  'Vi khuẩn nuôi cấy và định danh hệ thống tự động (bệnh phẩm khác)',
  'Vi nấm nuôi cấy và định danh hệ thống tự động',
  'Vi nấm nuôi cấy và định danh phương pháp thông thường',
  'Vi khuẩn kháng thuốc hệ thống tự động (bằng máy)',
  'Vi khuẩn kháng thuốc định tính',
  'Vi khuẩn nhuộm soi',
  'Vi nấm soi tươi',
  'Vi nấm nhuộm soi',
  'Neisseria meningitidis PCR',
  'Real-time PCR đa tác nhân chẩn đoán viêm màng não',
  'Các chỉ định chụp liên quan hệ thần kinh',
  'Các chỉ định chụp liên quan lồng ngực',
  'Các chỉ định chụp liên quan ổ bụng',
  'Các chỉ định chụp liên quan cơ xương khớp',
  'Các chỉ định chụp mạch máu',
  'Các chỉ định siêu âm ổ bụng – tiêu hoá',
  'Các chỉ định siêu âm gan mật tuỵ',
  'Các chỉ định siêu âm sản phụ khoa',
  'Các chỉ định siêu âm tiết niệu',
  'Các chỉ định siêu âm mạch máu',
  'Các chỉ định siêu âm tim- màng tim- màng phổi',
  'Các chỉ định siêu âm tinh hoàn',
  'YHHN Tim mạch (Xạ hình tưới máu cơ tim - SPECT/PET)',
  'Các chỉ định PET/CT & SPECT/CT chẩn đoán khối U (Khảo sát toàn thân / Cột sống / Xạ hình xương)',
  'Các chỉ định liên quan Hệ tiết niệu - thận (Xạ hình thận)',
  'Các chỉ định liên quan Hô hấp / hệ mạch máu (Xạ hình V/Q)',
  'Các chỉ định liên quan Phát hiện vi sinh vật / nhiễm khuẩn cấp (PET/CT)',
  'Điện tim'
];
